### ISSUE TITLE
Fails on UEFI Fedora 29 boot and with manual systemctl

### ISSUE THREAD

**Issue by rickhg12hs** [hadess/switcheroo-control#15] opened 2019-02-26 12:31 UTC
```bash
$ sudo G_MESSAGES_DEBUG=all /usr/sbin/switcheroo-control

** (process:5244): WARNING **: 13:23:29.119: switcheroo-control could not query vga_switcheroo status: Operation not permitted
```
```bash
$ dmesg|grep -i switcheroo
[    4.220215] VGA switcheroo: detected Optimus DSM method \_SB_.PCI0.PEG0.PEGP handle
[    4.452955] vga_switcheroo: enabled
[   40.331900] Lockdown: switcheroo-cont: debugfs is restricted; see man kernel_lockdown.7
```
```bash
$ journalctl -g switcheroo
-- Logs begin at Sat 2019-02-23 18:08:53 CET, end at Tue 2019-02-26 13:29:06 CET. --
Feb 23 18:59:48 localhost.localdomain kernel: VGA switcheroo: detected Optimus DSM method \_SB_.PCI0.PEG0.PEGP handle
Feb 23 18:59:48 localhost.localdomain kernel: vga_switcheroo: enabled
Feb 23 18:05:15 localhost.localdomain systemd[1]: Starting Switcheroo Control Proxy service...
Feb 23 18:05:15 localhost.localdomain kernel: Lockdown: switcheroo-cont: debugfs is restricted; see man kernel_lockdown.7
Feb 23 18:05:16 localhost.localdomain switcheroo-cont[781]: switcheroo-control could not query vga_switcheroo status: Operation not permitted
Feb 23 18:05:16 localhost.localdomain systemd[1]: switcheroo-control.service: Main process exited, code=exited, status=1/FAILURE
Feb 23 18:05:16 localhost.localdomain systemd[1]: switcheroo-control.service: Failed with result 'exit-code'.
Feb 23 18:05:16 localhost.localdomain systemd[1]: Failed to start Switcheroo Control Proxy service.
Feb 23 18:05:16 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=switcheroo-control c>
-- Reboot --
Feb 24 22:41:48 localhost.localdomain kernel: VGA switcheroo: detected Optimus DSM method \_SB_.PCI0.PEG0.PEGP handle
Feb 24 22:41:48 localhost.localdomain kernel: vga_switcheroo: enabled
Feb 24 21:42:19 localhost.localdomain systemd[1]: Starting Switcheroo Control Proxy service...
Feb 24 21:42:20 localhost.localdomain kernel: Lockdown: switcheroo-cont: debugfs is restricted; see man kernel_lockdown.7
Feb 24 21:42:20 localhost.localdomain switcheroo-cont[875]: switcheroo-control could not query vga_switcheroo status: Operation not permitted
Feb 24 21:42:20 localhost.localdomain systemd[1]: switcheroo-control.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 21:42:20 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=switcheroo-control c>
Feb 24 21:42:20 localhost.localdomain systemd[1]: switcheroo-control.service: Failed with result 'exit-code'.
Feb 24 21:42:20 localhost.localdomain systemd[1]: Failed to start Switcheroo Control Proxy service.
-- Reboot --
Feb 26 13:35:02 localhost.localdomain kernel: VGA switcheroo: detected Optimus DSM method \_SB_.PCI0.PEG0.PEGP handle
Feb 26 13:35:02 localhost.localdomain kernel: vga_switcheroo: enabled
Feb 26 12:35:38 localhost.localdomain systemd[1]: Starting Switcheroo Control Proxy service...
Feb 26 12:35:38 localhost.localdomain kernel: Lockdown: switcheroo-cont: debugfs is restricted; see man kernel_lockdown.7
Feb 26 12:35:38 localhost.localdomain switcheroo-cont[863]: switcheroo-control could not query vga_switcheroo status: Operation not permitted
Feb 26 12:35:38 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=switcheroo-control c>
Feb 26 12:35:38 localhost.localdomain systemd[1]: switcheroo-control.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 12:35:38 localhost.localdomain systemd[1]: switcheroo-control.service: Failed with result 'exit-code'.
Feb 26 12:35:38 localhost.localdomain systemd[1]: Failed to start Switcheroo Control Proxy service.
Feb 26 13:22:59 localhost.localdomain sudo[5210]:     rick : TTY=pts/2 ; PWD=/home/rick ; USER=root ; COMMAND=/usr/bin/gdbus introspect --system --dest net.hadess.Switc>
Feb 26 13:23:29 localhost.localdomain audit[5242]: USER_CMD pid=5242 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home>
Feb 26 13:23:29 localhost.localdomain sudo[5242]:     rick : TTY=pts/2 ; PWD=/home/rick ; USER=root ; ENV=G_MESSAGES_DEBUG=all ; COMMAND=/usr/sbin/switcheroo-control
```

**Comment by hadess** [comment] 2019-02-26 12:46
Duplicate of #12

**Closed as completed by hadess** 2019-02-26 12:46 UTC
